In [10]:
import numpy as np
def gaussEliminationWithoutPivoting(a,b,d):
    n = len(b)
    x = np.zeros(n,float)
    a = np.around(a,d)
    b= np.around(b,d)
    print(a)
    print(b)
    try:
    #Elimination
        for k in range(n-1):
            if a[k,k] == 0:
                raise ZeroDivisionError 
            for i in range(k+1,n):
                if a[k,i] == 0: 
                    continue
                factor = a[i,k]/a[k,k]
                factor = round(factor,d)
                print("Multiplication factor", factor)
                for j in range(k,n):
                    a[i,j] = np.around((a[i,j] - a[k,j]*factor),d)
                    
                b[i] = np.around((b[i] - b[k]*factor),d)
        print(a)
        print(b)

    #Back-substitution
        x[n-1] = np.around(b[n-1]/a[n-1,n-1],d)
        for row in range(n-2,-1,-1):
            sum_ax = 0
            for col in range(row+1,n):
                sum_ax += np.around(a[row,col] * x[col],d)
            x[row] = np.around((b[row] - sum_ax) / a[row,row],d)

    except ZeroDivisionError:
        print("Pivot element is zero.Cannot perform Gauss Elimination without Pivoting.")
    finally:
        return x
    
### MAIN ### 
a = np.array([[ 1.0417953454595328,  1.2140832859810209],
        [-0.46504172468086824,  2.8881838726411693]])
b = np.array([[-0.42106134],
        [ 0.13122502]])
d=6
sol = gaussEliminationWithoutPivoting(a,b,d)
print("The solution of the system of linear equations is: ",sol)

[[ 1.041795  1.214083]
 [-0.465042  2.888184]]
[[-0.421061]
 [ 0.131225]]
Multiplication factor -0.446385
[[ 1.041795  1.214083]
 [-0.        3.430132]]
[[-0.421061]
 [-0.05673 ]]
The solution of the system of linear equations is:  [-0.384894 -0.016539]


**Verification of the output using NumPy**

In [11]:
print("Solution verifcation using Numpy: ")
print(np.around(np.linalg.solve(a,b),6))

Solution verifcation using Numpy: 
[[-0.384895]
 [-0.016539]]
